name: Dispatch/Manual Execution
on:
  workflow_dispatch: {}
  push:
   paths:
      - .github/workflows/flat.yml
      - ./src/processors/Twitter.ts

jobs:
  Dispatched:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3.2.0
        with:
          http_url: https://old.reddit.com/r/PewdiepieSubmissions/top/.json?sort=top&t=day
          downloaded_filename: PewDiePieSubmissions.json

      - name: Fetch data
        uses: githubocto/flat@v3.2.0
        with:
          http_url: https://api.twitter.com/1.1/trends/place.json?id=1
          authorization: "Bearer ${{secrets.TWITTER_API_BEARER_TOKEN}}"
          downloaded_filename: twitter/trending-global-hashtags.json
          postprocess: ./src/processors/Twitter.ts

      - name: Fetch data
        uses: githubocto/flat@v3.2.0
        with:
          http_url: ${{ env.API_ENDPOINT }}
          downloaded_filename: OSRS-Active-Users.txt
          postprocess: ./src/processors/OSRS.ts

      - name: Discord Notifier
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

